version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bundle exec rackup -o 0.0.0.0 -p 3000

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    command: --socket=/run/mysqld/mysqld.sock


  worker:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: bundle exec sidekiq -r ./app.rb
