version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ruby app.rb

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development

  worker:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - .:/app
    command: ruby feedback_worker.rb
