source 'https://rubygems.org'

gem 'bundler'
gem 'mysql2', '0.5.5'
gem 'activerecord', '~> 6.1.7'
gem 'rspec'
gem 'sidekiq'
gem 'nokogiri'
gem 'dotenv'
gem 'faker'
gem 'builder'
gem 'rake'
gem 'sqlite3' , '1.4'
gem 'rack-contrib'